### PR TITLE
Add LikedFragment functionality and tests

### PR DESCRIPTION
**Pull request by jackstenglein**
Adds functionality to the LikedFragment and tests for the LikedFragment. Increases the timeout for the RecyclerViewItemCountAssertion to 26 seconds, the same as the default timeout for an IdlingResource.

### CODE REVIEW

**Comment by jackstenglein** [comment]
I noticed that the build is still failing, but made the pull request anyway so that I don't get blocked on that. We can discuss solutions to the test issue during our meeting today. The code does appear to work though, based on my manual tests and running the tests on my local machine.

**Comment by TianyiMu** [comment]
The pull request looks good to me. Since we are still having issue with tests and I feel the timeout probably cannot fix the flakiness completely, even if it is extended, I want to have Lin look at this as well during our meeting later today.

**Comment by jackstenglein** [comment]
> The pull request looks good to me. Since we are still having issue with tests and I feel the timeout probably cannot fix the flakiness completely, even if it is extended, I want to have Lin look at this as well during our meeting later today.

I have been having good results on the `ci` branch, where I have used an InstantTaskExecutorRule and performed database insertions on the main thread rather than a background thread. This seems to solve the problem and does not require the timeout. Of course, the downside is that the tests do not capture the true behavior of the app as well, given that they run everything on the main thread.

**Comment by TianyiMu** [comment]
I took a look at InstantTaskExecutorRule and I think using it in tests with livedata is fine. It is much better than adding artificial delay in test, and the delay really just mask the issue instead of fixing it. It is true that making everything run on the main thread is not the true threading behavior of the app, but the sequence does reflect the correct app behavior in that the list is updated after an observed livedata update. Feel free to update files in this pr with the test rule, or start another pr. Thanks

**Pull request merged**
